### ISSUE TITLE
Correlation Keys error on latest examples

### ISSUE THREAD

**Issue by asteel-gsa** [sartography/gsa-process-models#1]
Type: Bug

![image](https://github.com/sartography/gsa-process-models/assets/130377221/533ec333-aa92-40e6-b25d-c6e6a2b734f2)

Error on `correlation_keys`
[process_group.json](https://github.com/sartography/gsa-process-models/blob/b6cbff1600eebf6068b866a7db527e3a27ed701a/examples/process_group.json#L2)

**Comment by burnettk** [comment]
there's a PR up that should resolve this error: https://github.com/sartography/spiff-arena/pull/1467

**Comment by asteel-gsa** [comment]
Sweet! thank you @burnettk
Closing now as awaiting updates from main repo.
